baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Captain Contrary'
theme = 'cc'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
